package com.cric.cricketscoring.domain.usecase.tournament

import com.cric.cricketscoring.domain.model.FixtureStage
import com.cric.cricketscoring.domain.model.TournamentStatus
import com.cric.cricketscoring.domain.model.TournamentType
import com.cric.cricketscoring.domain.rules.FixtureGenerator
import com.cric.cricketscoring.domain.repository.TournamentRepository
import javax.inject.Inject

/**
 * Called when the GROUP stage is fully complete.
 * 1. Marks the top [qualifyingCount] teams as isQualified = true in the points table.
 * 2. Generates the next knockout stage fixtures.
 * 3. Updates tournament status to ONGOING if it was UPCOMING.
 *
 * For KNOCKOUT-only tournaments, the bracket was already generated by GenerateFixturesUseCase.
 * This use case only applies to LEAGUE and LEAGUE_PLUS_KNOCKOUT formats.
 */
class ResolveQualificationUseCase @Inject constructor(
    private val tournamentRepository: TournamentRepository,
    private val fixtureGenerator: FixtureGenerator
) {

    suspend operator fun invoke(
        tournamentId: String,
        knockoutStartDate: Long,
        matchGapMs: Long = 4 * 60 * 60 * 1000L
    ) {
        val tournament = tournamentRepository.getTournamentByIdSync(tournamentId) ?: return

        // Only applies to formats that have a knockout after league
        if (tournament.tournamentType == TournamentType.KNOCKOUT) return

        val table = tournamentRepository.getPointsTableSync(tournamentId)
            .sortedWith(
                compareByDescending<com.cric.cricketscoring.domain.model.PointsEntry> { it.points }
                    .thenByDescending { it.nrr }
                    .thenByDescending { it.won }
                    .thenBy { it.teamName }
            )

        if (table.isEmpty()) return

        // Number of teams that qualify for knockout (largest power-of-2 ≤ total teams / 2)
        val qualifyingCount = largestPowerOf2AtMost(table.size / 2).coerceAtLeast(2)

        // Mark qualifying teams
        val qualifiedTeamIds = table.take(qualifyingCount).map { it.teamId }.toSet()
        val updatedTable = table.map { entry ->
            entry.copy(isQualified = entry.teamId in qualifiedTeamIds)
        }
        tournamentRepository.savePointsTable(tournamentId, updatedTable)

        // Fetch TournamentTeam objects in qualification order
        val allTeams = tournamentRepository.getTeamsByTournamentSync(tournamentId)
            .associateBy { it.id }
        val qualifiedTeams = table.take(qualifyingCount).mapNotNull { allTeams[it.teamId] }

        if (qualifiedTeams.size < 2) return

        // Generate the appropriate knockout stage
        val stage = when (qualifyingCount) {
            8    -> FixtureStage.QUARTER_FINAL
            4    -> FixtureStage.SEMI_FINAL
            else -> FixtureStage.FINAL
        }

        // Clear any previously generated knockout fixtures for this stage (idempotent)
        tournamentRepository.deleteFixturesByStage(tournamentId, stage)

        val knockoutFixtures = fixtureGenerator.generateKnockout(
            qualifiedTeams    = qualifiedTeams,
            tournamentId      = tournamentId,
            stage             = stage,
            startDate         = knockoutStartDate,
            matchGapMs        = matchGapMs,
            matchNumberOffset = tournamentRepository.getTotalGroupMatchCount(tournamentId) + 1
        )
        tournamentRepository.upsertFixtures(knockoutFixtures)

        // Move tournament to ONGOING if still showing UPCOMING
        if (tournament.status == TournamentStatus.UPCOMING) {
            tournamentRepository.updateTournamentStatus(tournamentId, TournamentStatus.ONGOING)
        }
    }

    /** Returns the largest power of 2 that is ≤ n. */
    private fun largestPowerOf2AtMost(n: Int): Int {
        var p = 1
        while (p * 2 <= n) p *= 2
        return p
    }
}
